### ISSUE TITLE
Corrupted h5 file

### ISSUE THREAD

**Issue by tariq-hasan-zz** [kkweon/mnist-competition#1]
Hi, I think your model weights are corrupted.

I ran the `h5debug` command-line utility on the `.h5` weight files in your folder `model` and I get an error that the files cannot be opened!

Indeed, the function `load_models()` in 'evaluation.py', which attempts to open the `.h5` weight files in your folder `model`, fails to open them.

**Comment by maichm** [comment]
The same error as @tariq-hasan

**Comment by maichm** [comment]
@tariq-hasan I had try to open th .h5 file directly and find some interesting information on it. Maybe we should use command `git lfs clone https://github.com/xx/xxxx.git`, this will download three true h5 files from git lfs.

**Comment by hiteshnitetc** [comment]
All 3 .h5 file are corrupted.

**Comment by kkweon** [comment]
Looks like my git lfs is out of quota.
I will try uploading to S3 some day but I don't have the model file too. So, I have to wait for the quota to come back.

```
This repository is over its data quota. Purchase more data packs to restore access.
```

**Comment by hiteshnitetc** [comment]
@kkweon waiting
